#!/usr/bin/env bash
# One-time server setup for rezervuj-ma.online on the box (run as root, once).
# Expects the code already extracted to /opt/webstack/rezervuj (deploy.ps1 does that).
#
#   bash /opt/webstack/rezervuj/deploy/bootstrap-rezervuj.sh [http://192.168.100.50:8081]
#
# Creates the MariaDB database + user, writes .env, installs the quadlet and the
# scheduler timer, installs PHP dependencies, generates APP_KEY, runs the
# migrations and seeds the demo tenant. Safe to re-run: existing .env/DB are kept.
set -euo pipefail

APP=/opt/webstack/rezervuj
APP_URL="${1:-http://192.168.100.50:8081}"
CLI_IMAGE=docker.io/serversideup/php:8.4-cli
MARIADB_QUADLET=/etc/containers/systemd/mariadb.container

[ -d "$APP" ] || { echo "code not found in $APP – run deploy.ps1 first"; exit 1; }

# --- database ------------------------------------------------------------------
ROOT_PW=$(grep -oP '^Environment=MARIADB_ROOT_PASSWORD=\K.*' "$MARIADB_QUADLET")
DB_PW=$(openssl rand -hex 14)
if [ -f "$APP/.env" ] && grep -q '^DB_PASSWORD=.\+' "$APP/.env"; then
  DB_PW=$(grep -oP '^DB_PASSWORD=\K.*' "$APP/.env")
  echo ">> .env exists, keeping its database password"
fi
echo ">> database rezervuj + user"
podman exec -i web-mariadb mariadb -uroot -p"$ROOT_PW" <<SQL
CREATE DATABASE IF NOT EXISTS rezervuj CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'rezervuj'@'%' IDENTIFIED BY '${DB_PW}';
ALTER USER 'rezervuj'@'%' IDENTIFIED BY '${DB_PW}';
GRANT ALL PRIVILEGES ON rezervuj.* TO 'rezervuj'@'%';
FLUSH PRIVILEGES;
SQL

# --- .env ----------------------------------------------------------------------
if [ ! -f "$APP/.env" ]; then
  echo ">> writing .env"
  sed -e "s|__APP_URL__|${APP_URL}|" -e "s|__DB_PASSWORD__|${DB_PW}|" "$APP/deploy/env.production.example" > "$APP/.env"
  chmod 640 "$APP/.env"
fi

# --- systemd units -------------------------------------------------------------
echo ">> quadlet + scheduler timer"
install -m 644 "$APP/deploy/rezervuj.container" /etc/containers/systemd/rezervuj.container
install -m 644 "$APP/deploy/rezervuj-schedule.service" /etc/systemd/system/rezervuj-schedule.service
install -m 644 "$APP/deploy/rezervuj-schedule.timer" /etc/systemd/system/rezervuj-schedule.timer
install -m 755 "$APP/deploy/deploy-rezervuj.sh" /opt/webstack/deploy-rezervuj.sh
install -m 755 "$APP/deploy/set-public-url-rezervuj.sh" /opt/webstack/set-public-url-rezervuj.sh
systemctl daemon-reload

# --- dependencies + key ----------------------------------------------------------
mkdir -p "$APP/storage/framework/"{cache,sessions,views} "$APP/storage/logs" "$APP/bootstrap/cache"
chown -R 33:33 "$APP"
chmod -R ug+rwX "$APP/storage" "$APP/bootstrap/cache"
echo ">> composer install"
podman run --rm --network host -v "$APP":/var/www/html:Z -w /var/www/html "$CLI_IMAGE" composer install --no-dev --optimize-autoloader --no-interaction
if ! grep -q '^APP_KEY=base64:' "$APP/.env"; then
  echo ">> APP_KEY"
  podman run --rm --network host -v "$APP":/var/www/html:Z -w /var/www/html "$CLI_IMAGE" php artisan key:generate --force --no-interaction
fi
chown -R 33:33 "$APP"

# --- start ---------------------------------------------------------------------
echo ">> starting web-rezervuj"
# quadlet units are generated by systemd; the [Install] section already enables them at boot
systemctl start rezervuj.service
systemctl enable --now rezervuj-schedule.timer
for i in $(seq 1 20); do podman exec web-rezervuj true 2>/dev/null && break; sleep 2; done

echo ">> migrations + storage link + demo tenant"
podman exec -u 33 web-rezervuj php artisan migrate --force --no-interaction
podman exec -u 33 web-rezervuj php artisan storage:link --force >/dev/null 2>&1 || true
podman exec -u 33 web-rezervuj php artisan db:seed --class=DemoTenantSeeder --force --no-interaction
podman exec -u 33 web-rezervuj php artisan optimize:clear >/dev/null
podman exec -u 33 web-rezervuj php artisan config:cache >/dev/null
podman exec -u 33 web-rezervuj php artisan route:cache >/dev/null
podman exec -u 33 web-rezervuj php artisan view:cache >/dev/null

sleep 3
code=$(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:8081/ || echo 000)
echo ">> health check: HTTP $code"
echo "Done. Next: edit MAIL_* / PAYPAL_* / OPERATOR_* in $APP/.env, then: podman exec -u 33 web-rezervuj php artisan config:cache"
